clothes = ["ActiveFlex Yoga Leggings - Comfortable Workout Wear",
           "VintageVogue Floral Print Dress - Retro Charm in Modern Style",
           "TechThread Smart Fabric Shirt - Stay Connected in Style",
           "UrbanChic Denim Jacket - Effortless Street Style",
           "CozyComfort Cashmere Sweater - Stay Warm in Style",
           "ActiveFlow Sportswear Set - Performance and Fashion Combined",
           "ElegantEvening Gown - Red Carpet Ready",
           "ClassicFit Tailored Suit - Timeless Professional Attire",
           "CasualVibes Graphic Tee - Cool and Comfortable Everyday Wear",
           "VintageVogue Floral Print Dress - Retro Charm in Modern Style",
           "TechThread Smart Fabric Shirt - Stay Connected in Style",
           "BohoBreeze Bohemian Skirt - Free-Spirited Fashion",
           "AthleisureFlex Jogger Pants - Trendy and Versatile Activewear",
           "UrbanBlend Hooded Sweatshirt - Streetwear Chic",
           "EcoStyle Organic Cotton T-Shirt - Sustainable Fashion",
           "TechFit Smart Running Shoes - High-Tech Comfort",
           "ClassicTrend Plaid Scarf - Timeless Winter Accessory",
           "ActiveFlow Sports Bra - Supportive and Stylish",
           "VintageVogue Silk Blouse - Retro Elegance",
           "CasualEase Denim Jeans - Effortless Everyday Style",
           "CozyCraze Knit Sweater - Warmth with a Touch of Trend",
           "BusinessEssentials Suit Collection - Polished Professional Attire",
           "OutdoorPro Adventure Jacket - Ready for Exploration",
           "UrbanFlex Jogger Pants - Comfortable Streetwear",
           "GlamGrove Sequin Dress - Sparkle and Shine in Style",
           "ActiveForm Fitness Leggings - Stylish Workout Gear",
           "TechThread Smart Fabric Hat - Hi-Tech Fashion Statement",
           "VintageElegance Lace Blouse - Timeless Charm Redefined",
           "CasualChic Linen Shorts - Effortless Summer Style",
           "BusinessElite Suit Collection - Polished Professional Attire",
           "CozyCraze Lounge Robe - Luxurious Comfort at Home",
           "OutdoorExplorer Hiking Boots - Tread the Paths in Style",
           "ChicComfort Sweater Dress - Casual Elegance for Fall",
           "SportSwift Athletic Sneakers - Run with Speed and Style",
           "UrbanCanvas Graphic T-Shirt - Artistic Expression in Fashion",
           "EcoEssentials Sustainable Scarf - Green Fashion Choices",
           "CharmCity Cocktail Dress - Nightlife Glamour Personified",
           "WinterWardrobe Wool Coat - Stay Warm with Sophistication",
           "TechStyle Smartwatch Band - Personalized Tech Accessories",
           "VintageVibes Denim Skirt - Retro Fashion Revival",
           "ActiveLife Sporty Backpack - Carry Your Gear in Style",
           "UrbanEdge Leather Jacket - Urban Cool Redefined",
           "TrendyThreads Boho Chic Maxi Dress - Free-Spirited Fashion",

           ]

electronics = [
    "QuantumCore Gaming Laptop - Unleash Your Gaming Potential",
    "EcoCharge Solar-Powered Phone Charger - Energy on the Go",
    "QuantumSound Wireless Headphones - Immerse Yourself in Music",
    "PixelVision HD Webcam - Crystal Clear Video Calls",
    "SmartHomeHub Automation Kit - Control Your Home with Ease",
    "PowerSwift Fast Charging Power Bank - Charge on the Fly",
    "LuminaView 4K HDR Smart TV - Cinematic Entertainment at Home",
    "SecureSync Home Security Camera - Peace of Mind, Anywhere",
    "QuantumFit Smart Fitness Tracker - Your Personal Wellness Coach",
    "EchoSync Smart Speaker - Voice-Activated Convenience",
    "QuantumGlow LED Desk Lamp - Illuminate Your Workspace",
    "UltraSound Noise-Canceling Earbuds - Premium Audio Experience",
    "SmartHome Harmony Hub - Seamless Home Automation",
    "EcoCharge Portable Solar Charger - Power on the Go",
    "DigitalVision HD Action Camera - Capture Every Adventure",
    "GamerPrime Gaming Mouse - Precision for Pro Gamers",
    "WirelessLink Bluetooth Speaker - Music Anywhere, Anytime",
    "EssentialTech Laptop Stand - Ergonomic Workstation Solution",
    "InnoTech Fitness Tracker - Monitor Your Active Lifestyle",
    "PixelPerfect DSLR Camera - Professional Photography at Your Fingertips",
    "EcoGadget Solar-Powered Charger - Green Energy on the Go",
    "PixelPerfect DSLR Camera Bag - Stylish Protection for Gear",
    "SmartHome Harmony Remote - Control Your Space Effortlessly",
    "QuantumSpeed Gaming Mouse - Precision for Gamers",
    "DigitalHarbor HD Webcam - Crystal Clear Video Calls",
    "TechTalk Wireless Keyboard - Sleek and Silent Typing",
    "EcoPods Biodegradable Earbud Case - Sustainable Tech Accessories",
    "SmartWatchPro Fitness Tracker - Your Health at a Glance",
    "FutureTech VR Headset - Immerse Yourself in Virtual Worlds",
    "QuantumBeats Wireless Speaker - Music Anywhere, Anytime",
]

books = [
    "MysticQuest Fantasy Novel - Embark on an Epic Adventure",
    "ScienceWonders Exploration Guide - Discover the Wonders of the Universe",
    "HistoricalEchoes Non-Fiction Bestseller - Unraveling the Past",
    "PoetryHarbor Collection - Words that Touch the Soul",
    "MindfulnessJourney Meditation Guide - Find Inner Peace",
    "TechTales Sci-Fi Anthology - Futuristic Adventures Await",
    "CookbookCraze Culinary Masterpieces - Inspiring Recipes for Every Chef",
    "LifeUnfolded Self-Help Book - Navigate Challenges with Resilience",
    "KidLit Wonderland - Enchanting Stories for Young Readers",
    "ArtistryInspired Coffee Table Book - Visual Delights for Art Lovers",
    "TimelessTales Fiction Anthology - Stories to Transcend Eras",
    "MindMatters Self-Help Guide - Navigating Life's Challenges",
    "HistoricalChronicles Non-Fiction Masterpiece - Unveiling the Past",
    "SciFiSpectra Science Fiction Novel - Explore Otherworldly Realms",
    "PoetryEssence Collection - Verses that Speak to the Soul",
    "BusinessBlueprint Entrepreneurship Handbook - Strategies for Success",
    "CookbookHarbor Culinary Adventures - From Kitchen to Table",
    "HealthJourney Wellness Guide - Holistic Living Insights",
    "ArtisticVisions Coffee Table Book - A Visual Feast",
    "TravelExplorer Destination Diary - Journeys Around the Globe",
    "MindfulMinds Self-Help Handbook - Navigating Life's Challenges",
    "BusinessBlueprint Entrepreneurship Guide - Strategies for Success",
    "CookbookCreations Culinary Masterpieces - From Kitchen to Table",
    "HealthJourney Wellness Journal - Holistic Living Insights",
    "ArtisticVisions Coffee Table Photography Book - A Visual Feast",
    "TravelExplorer Destination Diary - Journeys Around the Globe",
    "FantasyQuest Epic Fantasy Series - A World of Imagination",
    "ScienceWonders Scientific Discoveries - Exploring the Unknown",
    "PoetryEssence Collection - Verses that Speak to the Soul",
    "ClassicReads Literary Classics Collection - Timeless Treasures",
    "ThrillerThrives Suspenseful Thriller Novel - Edge-of-Your-Seat Drama",
    "NovelNest Fiction Bestseller - Engaging Page-Turner",
    "SelfDiscovery Personal Growth Journal - Unleash Your Potential",
    "ArtfulExpressions Creative Writing Anthology - Words Unleashed",
]

health = [
    "VitalityMax Nutrient-Rich Protein Powder - Boost Your Energy",
    "MindfulMeditations Guided Relaxation CD - Stress Relief Anytime",
    "HeartGuard Smart Blood Pressure Monitor - Monitor Your Health at Home",
    "NaturalEase Herbal Tea Sampler - Wellness in Every Sip",
    "RevitalizeMe Daily Vitamin Pack - Essential Nutrients for Health",
    "PainRelief Pro Massage Gun - Soothe Muscles and Relieve Tension",
    "SleepSerene Aromatherapy Diffuser - Tranquil Nights Await",
    "PureGlow Organic Skincare Set - Nourish Your Skin Naturally",
    "FitFlex Resistance Band Set - Full-Body Workout Anywhere",
    "BalanceBoost Probiotic Supplement - Gut Health Support",
    "VitalityBoost Multivitamin Capsules - Daily Wellness Support",
    "MindfulMornings Meditation App - Start Your Day with Calm",
    "HeartHealth Pro Blood Pressure Monitor - Track Your Vital Signs",
    "NaturalZen Herbal Tea Collection - Serenity in Every Sip",
    "FitFlex Resistance Band Set - Versatile Home Workouts",
    "SleepWell Memory Foam Pillow - Sweet Dreams Every Night",
    "NourishMax Organic Protein Powder - Fuel Your Body Naturally",
    "AromaTherapy Essential Oil Diffuser - Relaxing Home Ambiance",
    "ZenFocus Meditation Cushion - Find Your Center",
    "FitnessFusion Workout DVD Set - Total Body Transformation",
    "SleepWell Memory Foam Pillow - Sweet Dreams Every Night",
    "NourishMax Organic Protein Powder - Fuel Your Body Naturally",
    "FitFlex Resistance Band Set - Versatile Home Workouts",
    "WellnessHarbor Meditation App - Calm Your Mind Anytime",
    "HeartHealth Pro Blood Pressure Monitor - Monitor Your Vital Signs",
    "AromaTherapy Essential Oil Diffuser - Relaxing Home Ambiance",
    "ZenFocus Meditation Cushion - Find Your Center",
    "FitnessFusion Workout DVD Set - Total Body Transformation",
    "PurePulse Fitness Tracker - Track Your Active Lifestyle",
    "NatureNutrition Superfood Smoothie Mix - Nutrient-Rich Blend",
    "BodyBalance Yoga Block Set - Support Your Yoga Practice",
    "FreshStart Detox Tea - Cleanse and Rejuvenate Your Body",
    "HealingHerbs Herbal Supplements - Nature's Remedies",
    "RevitalizeLife Wellness Retreat Package - Renew Your Spirit",
]

grocery = [
    "FarmFresh Organic Eggs - Pure and Wholesome Goodness",
    "GreenHarbor Superfood Smoothie Mix - A Burst of Nutrients",
    "PantryEssentials Whole Grain Pasta - Healthy and Hearty",
    "FreshHarvest Farmer's Market Bundle - Locally Sourced Goodness",
    "NatureNectar Honey Collection - Sweetness Straight from the Hive",
    "CrispHarbor Artisanal Potato Chips - Irresistible Snacking",
    "BountifulHarvest Fruit Basket - Nature's Candy Delivered",
    "GrainGroove Quinoa Variety Pack - Protein-Packed Grains",
    "SavorySpice Gourmet Seasoning Set - Elevate Your Culinary Creations",
    "DairyDelight Organic Milk Assortment - Farm-Fresh Goodness",
    "FarmersPride Organic Produce Box - Fresh from the Fields",
    "GreenGrove Superfood Blend - Nutrient-Packed Smoothie Booster",
    "PantryEssentials Whole Grain Pasta Bundle - Healthy Meal Foundation",
    "Nature'sHarvest Nut Mix - Snack Smart, Snack Natural",
    "FreshFlavors Farmers Market Selection - Culinary Delights",
    "OrganicOasis Coconut Water - Pure Hydration, Naturally",
    "EarthlyEats Plant-Based Protein Bars - Sustainably Sourced Snacks",
    "GourmetGroves Olive Oil Sampler - A Taste of Mediterranean Excellence",
    "SweetHarmony Honey Collection - Nature's Sweetest Gift",
    "PurePantry Gluten-Free Pasta - Healthy Choices for Every Meal",
    "Nature'sHarvest Nut Mix - Snack Smart, Snack Natural",
    "FreshFlavors Farmers Market Selection - Culinary Delights",
    "OrganicOasis Coconut Water - Pure Hydration, Naturally",
    "EarthlyEats Plant-Based Protein Bars - Sustainably Sourced Snacks",
    "SweetHarmony Honey Collection - Nature's Sweetest Gift",
    "BrewersBlend Artisan Coffee Beans - Rich and Robust Flavors",
    "WholesomeHarbor Whole Grain Cereal - Hearty Breakfast Option",
    "TropicalTreats Exotic Fruit Basket - Tropical Flavor Explosion",
    "PantryEssentials Rice Variety Pack - Versatile and Wholesome",
    "GourmetGroves Olive Oil Sampler - A Taste of Mediterranean Excellence",
    "BrewersBlend Artisan Coffee Beans - Rich and Robust Flavors",
]

products = {
    'clothes': clothes,
    'healthcare': health,
    'grocery': grocery,
    'books': books,
    'electronics': electronics
}
