# Generated by Django 4.2.8 on 2023-12-14 06:22

from django.db import migrations, models
import django.db.models.deletion
import products.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('website', models.CharField(max_length=100, validators=[products.validators.is_valid_url])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000, validators=[products.validators.is_valid_url])),
                ('total_review_count', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[products.validators.is_valid_rating])),
                ('price', models.IntegerField(validators=[products.validators.is_valid_price])),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.company')),
            ],
        ),
    ]
