# Generated by Django 4.2.8 on 2023-12-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='grocery', max_length=100),
            preserve_default=False,
        ),
    ]
