# Generated by Django 4.2.8 on 2023-12-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_company_id_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
    ]
